### ISSUE TITLE
Searching private key backups for non-Gmail accounts

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#105]
Need to do add a fix for searching the private key backups for non-Gmail accounts. 

Now we have the next template:
```
from:user@gmail.com
to:user@gmail.com
(subject:"Your CryptUp Backup"
 OR subject: "Your FlowCrypt Backup" 
 OR subject: "Your CryptUP Backup" 
 OR subject: "All you need to know about CryptUP (contains a backup)" 
 OR subject: "CryptUP Account Backup")
 -is:spam

```

And this search String works only for Gmail. Need to modify an algorithm using standard JavaMail API for non-Gmail accounts.

**Comment by tomholub** [comment]
Reopening to use the general search on gmail as well

**Comment by tomholub** [comment]
great, I'll do tests

**Comment by tomholub** [comment]
Unfortunately it's still failing for two of my friends. It just won't find any backups although it can find the backups on desktop.

I did some tests before (gmail search) on their accounts (I sent them a test apk) and the Gmail search was returning zero results, although the same gmail search pasted into Gmail webmail returned correct results. There is something weird with their IMAP - we need to debug it.

Let's make a test APK for them (separate branch) that will, instead of the load backup screen on setup, show debugging information.

We want to see number of search results for each of the following queries:
1) from: tom@cryptup.org
2) subject: "Your CryptUp Backup"
3) subject: "Your FlowCrypt Backup"
4) subject: "Your CryptUP Backup"
5) subject: "All you need to know about CryptUP (contains a backup)"
6) subject: "CryptUP Account Backup"
7) from: useremailaddress@gmail.com
8) to: useremailaddress@gmail.com

These are 8 different separate queries for us to find out which ones fail / which ones have some results. So the screen will show:
```
Test 1: 4 results
Test 2: 0 results
...
```

If we find out that all show 0 results, we can submit a bug to Google. If some show 0 results, maybe we can adjust the search query.

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android/commit/0d760b629e531a46ddcc4730ba38e307e3a13e40 and https://github.com/FlowCrypt/flowcrypt-android/commit/59b8f869788167030e87a377208944286a901859 contain changes for the debug APK build. I created two options

1. https://github.com/FlowCrypt/flowcrypt-android/commits/issue_105_native_search - This example of native JavaMail API usage (I mean clear IMAP).

2. https://github.com/FlowCrypt/flowcrypt-android/commits/isssue_105_gmail_search - This example of GMAIL X-GM-RAW usage.

For me, both of this options give equivalent result.

**Comment by tomholub** [comment]
Perfect, I'll have them test it.

**Comment by tomholub** [comment]
@DenBond7 I think we found it. The debug screen was very helpful. It does not search archived email in either case! :)

Please archive your backup in Gmail and try.

**Comment by tomholub** [comment]
When this is fixed, we can release v9. I suggest to use IMAP method in all cases, but up to you - you can also use Gmail if you think it makes sense.

**Comment by DenBond7** [comment]
> Please archive your backup in Gmail and try.

@tomholub Yes, of course. And this is not a bug, this is just the app logic. The example code:

```
IMAPFolder imapFolder = (IMAPFolder) store.getFolder(JavaEmailConstants.FOLDER_INBOX);
imapFolder.open(Folder.READ_ONLY);

List<String> keys = new ArrayList<>();

SearchTerm searchTerm = SearchBackupsUtil.generateSearchTerms(accountDao.getEmail());
Message[] foundMessages = imapFolder.search(searchTerm);
```
`getFolder(JavaEmailConstants.FOLDER_INBOX);` means that we open the INBOX folder and try to find backups here.

I propose next solution: for Gmail, the app will search backups in the ARCHIVE folder and for another email providers the app will search backups in the INBOX folder.

**Comment by DenBond7** [comment]
As I can see the Gmail (web app) can find backups in all folders. But I can work simultaneously only with one folder in the app. If need I can do a search in all folders but then I must do it in the loop.

**Comment by tomholub** [comment]
Yes, we have to loop through all of the folders. That's the only way to make sure to find the backup - user may have moved it.

**Comment by DenBond7** [comment]
Ok, I will do it.

**Comment by DenBond7** [comment]
@tomholub Please test the current version in the branch "0.0.9". If the search works well we can close this issue.

**Comment by tomholub** [comment]
Will do, thanks!

**Comment by tomholub** [comment]
all good
