### ISSUE TITLE
apk size increased from 40 to 100 mb in version 1.0.7

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1182]
![image](https://user-images.githubusercontent.com/6306961/115461860-6d813b00-a219-11eb-9262-d212bbb9710f.png)

I forgot if we discussed this at the time, or if this was an oversight.

**Comment by tomholub** [comment]
Enterprise release sizes show a similar bump.

**Comment by DenBond7** [comment]
it's expected behavior 
ref #890 

![image](https://user-images.githubusercontent.com/2863246/115503052-840dad80-a27e-11eb-814f-464d4842009e.png)


https://developer.android.com/topic/performance/reduce-apk-size#extract-false
ref https://www.reddit.com/r/androiddev/comments/f9u9x4/apk_size_increased_2x_on_android_gradle_360/?sort=old

**Comment by tomholub** [comment]
I see. Got it

**Comment by DenBond7** [comment]
By the way, after dropping Node we will decrease the app size a lot.

**Comment by tomholub** [comment]
I can imagine :)
