### ISSUE TITLE
updating primary key with newer version of the same key

### ISSUE THREAD

**Issue by seisvelas** [FlowCrypt/flowcrypt-android#1286]
A user's key expired, so they updated the expiration date via Kleopatra and loaded into the browser extension with no problem. But the Android app is still using the old version of the key. And they're not sure how they should change it to the new version.

If they try to upload the new version, the app rejects it for being the same key. They can't delete the existing key because it's the only one.

My best workaround is to upload a random temporary key just so they can delete their original key, then upload the new version of the key, then delete the temporary key, leaving the new version of their original key as their only one. 

How are users supposed to do this?

**Comment by DenBond7** [comment]
> If they try to upload the new version, the app rejects it for being the same key. They can't delete the existing key because it's the only one.
My best workaround is to upload a random temporary key just so they can delete their original key, then upload the new version of the key, then delete the temporary key, leaving the new version of their original key as their only one.

You are totally right. For now, it's the best option. Unfortunately, there is no easy way to replace a key via the app yet.

> a random temporary key

For that, he can use for example https://pgpkeygen.com/

**Comment by tomholub** [comment]
They could log out of the app, which will delete previous keys, and set it up again with the newly updated key.

**Comment by imajeff** [comment]
Just to be clear: After editing the expiration date in Keopatra you cannot import it to the flowcrypt app with "no problem" but it will clearly say 0 keys updated. So obviously the problem is mis-worded. That's why "log out of the app" will not magically load in any updated key. No keys were updated because the app does not support detecting a change in the same key ID but simply will not import the updated key because it is the same key ID.

Three problems concerning this problem worth solving:

1. Importing should detect at least the expiration change of the same key ID and replace the old one.
2. No option to create new key in the app makes extremely tedious because I don't simply always have a different computer to create keys and then a way to even copy a file directly to the phone with secret keys, but all that only to discard the new key since it was only a placeholder to delete again afterwards.
3. App will not even display any expiration date, nor tell me the reason it could not send when it was expired. Needs to at least display both creation and expiration dates.

**Comment by tomholub** [comment]
Thank you Jeff for the input. 

> Importing should detect at least the expiration change of the same key ID and replace the old one.

Yes - we could address this one in this issue.

> No option to create new key in the app makes extremely tedious because I don't simply always have a different computer to create keys and then a way to even copy a file directly to the phone with secret keys, but all that only to discard the new key since it was only a placeholder to delete again afterwards.

I've filed an issue here https://github.com/FlowCrypt/flowcrypt-android/issues/1291 for much later

> App will not even display any expiration date, nor tell me the reason it could not send when it was expired. Needs to at least display both creation and expiration dates.

Agree. This is the current behavior on browser extension. Filed issue: https://github.com/FlowCrypt/flowcrypt-android/issues/1292

----------------------

Currently we are in the middle of architectural transitions on the app so it's hard to squeeze some new functionality in while we are toiling away on the transition itself. Unfortunately we probably won't be able to get to this for another two to three months.

( @DenBond7 general logic for replacing primary keys with newer versions of the same key will definitely be needed, because upcoming integration with Email Key Manager will also rely on once in a while updating or replacing keys before they expire - so we'll probably look into this in August )

Thank you Jeff again for the feedback!

**Comment by tomholub** [comment]
@DenBond7 you will be able to tell it's the same key by comparing the primary fingerprint (which you probably already do, showing the error)

Instead of the error, if the new key has `lastSignature` (or sometimes called `lastModified`) newer than the old key, then replace the old key with this new key in storage and show visual feedback that this was done. 

If the new key is older then existing key, then tell the user that the key they already have has a more recent signature on it then the key they are trying to import, therefore it was skipped.

**Comment by DenBond7** [comment]
Clarification

- This one will resolve updating an existing key from `Settings -> Keys -> Key details` 
- #1287 will resolve importing a newer version from `Settings -> Keys -> Import`

**Comment by DenBond7** [comment]
@tomholub @sosnovsky I've created a base version that has the requested functionality. What do you think?

![ezgif com-optimize](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/698169be-f3ca-472f-a3b8-679f42a3b354)4

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/401d1c92-31af-4b79-8bac-a8025bb338be)

**Comment by sosnovsky** [comment]
> @tomholub @sosnovsky I've created a base version that has the requested functionality. What do you think?

Looks good 👍

**Comment by DenBond7** [comment]
Test cases

- [ ] have a key, import a newer version -> success
- [ ] have a key, import a newer version with missed expected email address. -> don't show `use this key`, show a hint about the missed email address.
- [ ] have a key. Import the same key -> don't show `use this key`, show a hint about the same key.
- [ ] have a key. Import an older key -> don't show `use this key`, show a hint about the older key.
- [ ] have a key. Import a different key -> don't show `use this key`,  show fingerprint `MISMATCH` hint

@sosnovsky Please look at these cases. Maybe you will have a few more.

**Comment by DenBond7** [comment]
@sosnovsky I need to clarify a few moments

### First case
1. Let's imagine we have one imported key with `PassphraseType.RAM`
2. A user is trying to update it from `Settings -> Keys -> Key details`
3. If a pass phrase is not provided should the app ask the user to provide the pass phrase before proceeding?

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/2ec18371-003b-49d6-b9be-9f88e6828760)

### Second case 
1. Let's imagine we have one imported key with `PassphraseType.RAM`
2. A user is trying to update it from `Settings -> Keys -> Key details`
3. he provides a new good key and a pass phrase. This screen looks like this one

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/46fd5c03-358d-4cf4-904d-36dda38a6cdc)

5. Will it look correct if the user will be able to use `Save pass phrase` for the newer version? I mean he will be able to change the passphrase type.

**Comment by sosnovsky** [comment]
> If a pass phrase is not provided should the app ask the user to provide the pass phrase before proceeding?

Yes, user should enter correct passphrase before being able to update private key.

> Will it look correct if the user will be able to use Save pass phrase for the newer version? I mean he will be able to change the passphrase type.

Yes, looks good, but let's preselect current type by default - so if user current passphrase has type `PassphraseType.RAM` then `Remember pass phrase temporarily` should be selected.

**Comment by DenBond7** [comment]
> Yes, user should enter correct passphrase before being able to update private key.

Got it. In that case, I have a new question.

This one https://github.com/FlowCrypt/flowcrypt-android/issues/1287 covers a case when we update private keys via `Settings -> Keys -> Import.` It will not be easy to apply there the same logic there. I see the following:

1. Don't allow updating keys with `PassphraseType.RAM`
2. Or even don't allow updating keys via this action. Only import new keys. If a user needs to update some key he should go to `Settings -> Keys -> Key details` and do updating there. It will be clear. IMHO I prefer this option.

**Comment by sosnovsky** [comment]
> Or even don't allow updating keys via this action. Only import new keys. If a user needs to update some key he should go to Settings -> Keys -> Key details and do updating there. It will be clear. IMHO I prefer this option.

Will it be possible to redirect user to `Key details` screen when he tries to update existing key with `PassphraseType.RAM` through `Settings -> Keys -> Import`?

Then it'll work this way:
- key with saved passphrase - can be updated from `Settings -> Keys -> Import` and `Settings -> Keys -> Key details`
- key with `PassphraseType.RAM` with provided passphrase - can be updated from `Settings -> Keys -> Import` and `Settings -> Keys -> Key details` too
- key with `PassphraseType.RAM` without provided passphrase - when trying to update from `Settings -> Keys -> Import` will show warning `Please provide passphrase for current key before updating` and redirect user to `Settings -> Keys -> Key details`

What do you think about such logic?

**Comment by DenBond7** [comment]
You are talking about a case when a user is trying to import an updated version of ONE key. But `Settings -> Keys -> Import` supports importing a few keys at once. For example, a user can have a file where can be the following content:

- new key
- new key
- existing key with extended expiration
- existing key with updated info

The user can import all of these keys if he has pass phrases on this screen

![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/74b7aa0b-62ec-4c93-b1cf-daf629f50cd1)
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/7d247ed8-0811-48d8-933d-4da507856f09)
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/89488b80-800a-4ae3-853c-29713f68906d)


That's why I propose to allow **ONLY IMPORT** there. It will be clear. If you need to add a new key -> use Import, if you need to update an existing key -> go to the key details screen.

**Comment by sosnovsky** [comment]
> That's why I propose to allow ONLY IMPORT there. It will be clear. If you need to add a new key -> use Import, if you need to update an existing key -> go to the key details screen.

Ah, I see now, let's do it this way then. Just need to have some message for user saying `To update existing key please go to  Settings -> Keys -> Key details` when user tries to import updated version of existing key.
