### ISSUE TITLE
Refreshing inbox - original items show old state

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#130]
1) open inbox and see some email items
2) go to gmail on desktop and read some emails, archive some emails, receive some new emails
3) refresh inbox in the app

You will see the new emails show up on top, but the archived emails will not disappear, and read emails will still show as unread.

What can be done to improve this?

**Comment by DenBond7** [comment]
Now the refresh function only loading new messages. It gets the last UID in
a folder from a local database, retrieves the next UID for a remote folder
and tries receiving massages from a range [last UID in the local database,
the next UID of the remote folder].

< What can be done to improve this?

I will do research this issue and then will add more details.

On Nov 4, 2017 17:27, "Tom J" <notifications@github.com> wrote:


   1. open inbox and see some email items
   2. go to gmail on desktop and read some emails, archive some emails,
   receive some new emails
   3. refresh inbox in the app

You will see the new emails show up on top, but the archived emails will
not disappear, and read emails will still show as unread.

What can be done to improve this?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/FlowCrypt/flowcrypt-android/issues/130>, or mute the
thread

**Comment by DenBond7** [comment]
@tomholub Now all cached messages will be sync after we do refreshing. I added support add/delete/update status. That's ready for testing.

Performance info (for a history):
```
11-21 16:21:01.485 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: Request info about = 10000 messages
11-21 16:21:01.485 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: Total server time = 1158
11-21 16:21:02.089 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: getMap time = 604
11-21 16:21:02.097 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: messagesUIDInLocalDatabase time = 8
11-21 16:21:02.148 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: generateDeleteCandidates time = 51
11-21 16:21:02.149 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: Delete time = 1
11-21 16:21:02.182 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: generateNewCandidates time = 32
11-21 16:21:02.183 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: Add new rows time = 1
11-21 16:21:02.293 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: generateUpdateCandidates time = 110
11-21 16:21:02.293 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: Update rows time = 0
11-21 16:21:02.293 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: updateLocalContactsIfMessagesFromSentFolder time = 0
11-21 16:21:02.294 6424-6576/com.flowcrypt.email.debug D/DEBUG_PERFORMANCE: Total request time = 1967
```

Connection type: WIFI, speed: 50 Mbit/s, updated info about 10000 messages in the local database. Total = around 2 seconds.

**Comment by tomholub** [comment]
Works great
