### ISSUE TITLE
Fix "signed msg that looks like encrypted" (Kotlin)

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1357]
![image](https://user-images.githubusercontent.com/2863246/126609922-2391afc6-ae24-45b6-b86a-0b6d513ee0d8.png)

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1355#issuecomment-884738873_

**Comment by tomholub** [comment]
These screenshots are funny because both the before, and the after, are wrong.

However, this is such a rare occurrence that we can leave it until much later. And the new behavior is actually an improvement over the previous one.

The fix should be, that in this case, the border should show gray instead of green, because this message is only signed. Otherwise it looks correct.

**Comment by DenBond7** [comment]
![image](https://github.com/FlowCrypt/flowcrypt-android/assets/2863246/ac3cdb2c-fedc-45a5-82dd-5e0f0deb25f5)
