### ISSUE TITLE
Design: Adaptive Icons

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#136]
We can add Adaptive Icons https://youtu.be/5MHFYfXno9c

**Comment by tomholub** [comment]
We could, I just wonder if it's possible to restrict it to not use circle icon. Our logo is very simple and the square is quite important in it, it basically becomes a different logo if you put it in a circle. Although on Twitter I didn't have much choice: https://twitter.com/FlowCrypt

Maybe once we have a more distinct logo, we could use the adaptive icons because by then our logo will be clear regardless what shape you put it into.

**Comment by DenBond7** [comment]
https://github.com/nickbutcher/AdaptiveIconPlayground

**Comment by tomholub** [comment]
You can ignore my comment above
