### ISSUE TITLE
sometimes - my own email wrongly in cc when I click reply

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1392]
To reproduce:
1) find an encrypted email from `user@example.com` to `me@example.com`
2) click reply all on that email
3) `me@example.com` unexpectedly shows in `Cc` in gray - loading forever. In fact, this email has public key on it.

![image](https://user-images.githubusercontent.com/6306961/128852638-1098b5d8-9f6b-46a7-b3d3-1a50510ef0fc.png)

But it only happens sometimes. It seems I can reproduce this in about 50% of attempts. In the other attempts, `me@example.com` does not show (or quickly disappears? not sure), so nothing to load forever.

Observed with @veronkeller

**Comment by DenBond7** [comment]
> me@example.com unexpectedly shows in Cc

interesting... I've found that JavaMail always returns `ReplyTo`

Let me attach an example of the source code

![image](https://user-images.githubusercontent.com/2863246/129535973-53b4521e-f55c-4269-adcf-f902c935a32b.png)

This bug in most cases relates to Gmail behavior (threads). Because here we can see sent messages.
For the sent message `getFrom` return the sender address.

I think we can compare `replyTo` address with the sender address and skip `replyTo` usage if it equals the sender address.
