### ISSUE TITLE
document with oauth client ids are used for which build

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1457]
especially which were used for enterprise prod build - I understand there were two client ids? One for mail provider and one for calling our backend?

**Comment by DenBond7** [comment]
As I remember we already talked about. I will try to find history.

**Comment by DenBond7** [comment]
I use just OAuth 2.0 Client IDs for both flavors(customer and enterprise) if we are talking about `SignIn` and `https://mail.google.com/` scope

this one https://github.com/FlowCrypt/flowcrypt-android/blob/e336f06c1872ee644a49cfe695b8b3d1ae1d59e5/FlowCrypt/src/main/java/com/flowcrypt/email/util/google/GoogleApiClientHelper.kt#L29

**Comment by DenBond7** [comment]
@tomholub Please check if it looks good and informative.

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/133795973-445426be-2911-4662-a13a-b3147cf772f0.png)

**Comment by tomholub** [comment]
could for example delete the debug one, see if it still works

**Comment by DenBond7** [comment]
- `FlowCrypt Android Web Application for id_token` - we use it to communicate with our backend(customer + enterprise)
- `FlowCrypt Android App Enterprise Debug` - we use it to be able to use SignIn for enterprise debug builds
- `FlowCrypt Android App Enterprise` - we use it to be able to use SignIn for enterprise builds
- `FlowCrypt Android App` - we use it to be able to use SignIn for customer builds
- `FlowCrypt Android App Debug` - we use it to be able to use SignIn for customer debug builds

After some manipulations, we can have the following 
- `FlowCrypt Android Web Application for id_token` - we use it to communicate with our backend(customer + enterprise)
- `FlowCrypt Android App Enterprise` - we use it to be able to use SignIn for enterprise builds(need to add the second `SHA1 + package` of the debug build)
- `FlowCrypt Android App` - we use it to be able to use SignIn for customer builds(need to add the second `SHA1 + package` of the debug build)

Or
- `FlowCrypt Android Web Application for id_token` - we use it to communicate with our backend(customer + enterprise)
- `FlowCrypt Android App` - we use it to be able to use SignIn for all builds(need to have 4 cases of `SHA1 + package`: customer, customerDebug, enterprise, enterpriseDebug)

It depends on your needs. We can leave all things as-is(I prefer it). Because changes in that settings sometimes affect the app and we will have to change the package to be able to use SignIn(I had such experience). I think we can play with debug versions, but it will be better to leave prods as-is.

**Comment by DenBond7** [comment]
> It depends on your needs. 

I meant management, analyzing statistics, and so on.

**Comment by tomholub** [comment]
Ok. That means that all apps currently use two client ids. Could you please document this in some hollistic manner - maybe a table of builds and which exact client ids (copy the client id string) they use and so on. Customers sometimes need these strings to specifically allow them.

(by the way, where in the codebase are these other 4 client ids set?)

**Comment by DenBond7** [comment]
> maybe a table of builds and which exact client ids (copy the client id string) they use and so on

Will do

> (by the way, where in the codebase are these other 4 client ids set?)

We only use this one `374364070962-n83b6asllhfkhij6slijr61576lqqi3v.apps.googleusercontent.com`(FlowCrypt Android Web Application for id_token) in the codebase

**Comment by tomholub** [comment]
I see, so all of this is (except for `74364070962-n83b6asllhfkhij6slijr61576lqqi3v.apps.googleusercontent.com`) decided purely by the console sha-1 fingerprints - no reference in our codebase.

**Comment by DenBond7** [comment]
> I see, so all of this is (except for `74364070962-n83b6asllhfkhij6slijr61576lqqi3v.apps.googleusercontent.com`) decided purely by the console sha-1 fingerprints - no reference in our codebase.

Correct

**Comment by DenBond7** [comment]
| Build type | Package | OAuth 2.0 Client ID for API(flowcrypt)| OAuth 2.0 Client ID for email access|
| :---: | :--- | :--- | :--- |
| `Customer` | `com.flowcrypt.email` | `374364070962-n83b6asllhfkhij6slijr61576lqqi3v.apps.googleusercontent.com` | `374364070962-bs819lhrqvkv3nthh2cdb3i8fqirv3de.apps.googleusercontent.com` |
| `Customer Debug` | `com.flowcrypt.email.debug` | `374364070962-n83b6asllhfkhij6slijr61576lqqi3v.apps.googleusercontent.com` | `374364070962-ejldjom41l965jm913cgbopn4u9g65hd.apps.googleusercontent.com` |
| `Enterprise` | `com.flowcrypt.email.enterprise` | `374364070962-n83b6asllhfkhij6slijr61576lqqi3v.apps.googleusercontent.com` | `374364070962-hmqdikqd0o5tuogldli60k380jem9mu5.apps.googleusercontent.com` |
| `Enterprise Debug` | `com.flowcrypt.email.enterprise.debug` | `374364070962-n83b6asllhfkhij6slijr61576lqqi3v.apps.googleusercontent.com` | `374364070962-j3hb01jo4n97f213aoffncjnt35b2chb.apps.googleusercontent.com` |

**Comment by tomholub** [comment]
Thanks!

**Comment by DenBond7** [comment]
@tomholub or @martgil 

>Customers sometimes need these strings to specifically allow them.

Do we have the above table somewhere in our docs?

ref https://github.com/FlowCrypt/flowcrypt-android/issues/2108

**Comment by martgil** [comment]
Hi sir, @DenBond7 we don't have any documentation for it yet. Also, a user shares a helpful suggestion for us to consider.

> Displaying it in the client itself would be the next best thing, although I would prefer the documentation page for the added security.
