### ISSUE TITLE
A few pub keys for a recipient. Creating an encrypted message

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1540]
Creating an encrypted message

When we create a new message we check if a user has a pub key. But before we had one user <-> one pub key.
After changes a user can have a few pub keys with different states, for example:
1) `one good` + `one expired`
2) `one good` + `one good`
3) `one expired` + `one expired`

How to handle such cases?
What color should I use for chips in these cases?

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1188#issuecomment-963216404_

**Comment by tomholub** [comment]
For color choice, see public key ordering + coloring: https://github.com/FlowCrypt/flowcrypt-android/issues/1188#issuecomment-947789890 . As before, if color of any recipient is non-green, then they don't have any good public key and therefore message cannot be sent - they should see a modal.

Here are also some test emails for manual testing: https://github.com/FlowCrypt/flowcrypt-ios/issues/744

Here are modal messages listed: https://github.com/FlowCrypt/flowcrypt-ios/issues/732

For public key choice during encryption, filter recipient keys to only choose the valid ones.

Let's say that your example are three recipients:

> A: one good + one expired
> B: one good + one good
> C: one expired + one expired

These happen to be correctly ordered public keys as per https://github.com/FlowCrypt/flowcrypt-android/issues/1188#issuecomment-947789890 (valid first). Nevertheless, because of C, the user will se an error modal.

For this example:

> A: one good + one expired
> B: one good + one good

The message will be encrypted for 3 public keys for recipients which is [A-good-1, B-good-1, B-good-2] plus also all of my own public keys that are valid & match by the matching logic based on sender email that we already have. So if I have two such matching keys of my own, then in this situation I could be encrypting for 5 pubkeys total to send to these two recipients.

**Comment by DenBond7** [comment]
Based on all info that I read I'd like to add more details. I see the following(if not first, then second, and so on)

- **GREEN** -> a recipient has at least one usable key (non-revoked, non-expired, well parsed. To be short - a good key)
- **ORANGE** -> a recipient has at least one usable key, but it's expired
- **RED** -> a recipient has at least one pub key, but it's not usable(wrongly parsed and so on)
- **GRAY** -> a recipient has no pub keys

on this stage, I don't need to sort keys. Just need to check conditions to define a color.

**Comment by tomholub** [comment]
By sorting and then evaluating the first (best) key, it makes the logic simple and fool-proof. Also consistent with other platforms.

Your list doesn't mention revoked keys. Is the current code checking if the key is revoked?

**Comment by tomholub** [comment]
You can nanually with this email. Can also load the public key into your mocks / automated tests.

<img width="649" alt="image" src="https://user-images.githubusercontent.com/6306961/140952047-07c2ab1c-11f1-401a-9444-f137ffbaaa7a.png">

**Comment by tomholub** [comment]
<img width="317" alt="image" src="https://user-images.githubusercontent.com/6306961/140952378-5c600aa3-3592-4aab-a9a3-0b57183a154e.png">

**Comment by tomholub** [comment]
PGPainless should give you information about whether a public key is revoked or not. If not sure how, ask Paul. Maybe the PGPainless readme needs a section about parsing keys and getting details out of them?

**Comment by DenBond7** [comment]
Got it, thanks. I will check.

**Comment by IvanPizhenko** [comment]
what about revoked keys?

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/141084202-3167cb20-8d21-439a-ba34-20b3a07af1c0.png)
![image](https://user-images.githubusercontent.com/2863246/141086398-41625be4-2e9e-466e-97d5-6203b292d914.png)

**Comment by tomholub** [comment]
very good

**Comment by tomholub** [comment]
Here's a few more test emails for you, that have combinations of keys. There are no google accounts behind them, so you can send emails and they will bounce back. Which should be enough for manual testing. All `@flowcrypt.com`

```
valid.expired
valid.revoked
valid.expired.revoked
```
