### ISSUE TITLE
A few pub keys for a recipient. Encryption and signing.

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1541]
Encryption and signing. NEW messages

Imagine that I have the following records in the local database

```
1| FINGERPRINT| sender@flowcrypt.test | KEY
2| FINGERPRINT| recipient@flowcrypt.test | KEY1
3| FINGERPRINT| recipient@flowcrypt.test | KEY2
```

I'm a `sender`. I'd like to encrypt and sign a message for a `recipient`. What combination of keys should I use?

1. `KEY` + `KEY1`
2. `KEY` + `KEY2`
3. `KEY` + `KEY1` + `KEY2`

_Originally posted by @DenBond7 in https://github.com/FlowCrypt/flowcrypt-android/issues/1188#issuecomment-963221766_

**Comment by tomholub** [comment]
For encryption, use all of them, but:
 - filter only valid keys of recipient per #1540 
 - reuse our existing mechanism to choose sender's key based on sender email, but instead of choosing one, make it a filter. That means, any of my keys that contain the sender email address in any of their uids will get included. Also, if there isn't any valid key, show a modal about my own keys as before

For signing:
 - keep logic as before: sign with one chosen key as per the existing logic (we've already had several private keys before this milestone, so no change here)

**Comment by DenBond7** [comment]
**For encryption**

> filter only valid keys of recipient per

Not revoked and not expired? right?

> That means, any of my keys that contain the sender email address in any of their uids will get included

Before we just used the first from the matching list. So there no too many changes. That's great :)

**Comment by tomholub** [comment]
> > filter only valid keys of recipient per
> 
> Not revoked and not expired? right?

And being generally usable for encryption - having primary uid, appropriate signatures and so on - overall a valid key (there should be PGPainless method to validate. Originally it was something like `.usableForEncryption`

**Comment by DenBond7** [comment]
Got it. I will check this info. Before we didn't do that.

**Comment by tomholub** [comment]
If we didn't do that before, and didn't run into big issues, then maybe can skip it for now as well. File an issue for later.
