### ISSUE TITLE
treat SSL error when opportunistically calling FES - only on consumer release

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1565]
Hello team,

We have a user experiencing a problem when logging into their account. The user is using an email with a different domain `user @example.com` similar to what we have using the `@ flowcrypt.com`. The app sends requests to `fes.${domain.tld}` and causes some SSL-related issues. This prevents the user from logging into the app.

![image](https://user-images.githubusercontent.com/46025304/142367314-7347d697-9d9c-46bf-8a19-c395334df7b4.png)

I found a GitHub issue from okhttp that might be helpful.
https://github.com/square/okhttp/issues/1467

Please let me know if there's anything else I could do to help.

Reference: 
https://mail.google.com/mail/u/2/#inbox/FMfcgzGlksJGCzLxKNPQfpRTtskpMzsv
https://mail.google.com/mail/u/2/#inbox/FMfcgzGllChxkCZLjDPVZwlBglTGjFMM

**Comment by DenBond7** [comment]
@martgil Hi Mart,

Thank you for reporting this. It's a good one.

**Comment by martgil** [comment]
You're welcome, sir. Thanks!

**Comment by martgil** [comment]
@DenBond7 Good Morning, sir! A concerned user asked for an update on this issue. Do we have an estimated ETA for this issue to get fixed?

Kind regards,

**Comment by tomholub** [comment]
For the fix here:
 - regular release: SSL errors can be ignored, treat as no FES available
 - enterprise: SSL errors are treated as an error, the way it is now. Don't let user proceed.

**Comment by tomholub** [comment]
@martgil please use emails at `example.com` or `something.text` to avoid triggering the bot.

@DenBond7 Also, this only applies to situations when we call FES opportunistically - when we don't know if FES is running or not. Once FES was known to be running successfully at least once, we treat API calls like any other API call - failures must continue failing. This especially applies to #1375 - if this SSL error happened during refetch, that's an error. Should at least produce a toast to let the user know it couldn't be refetched due to SSL error.
