### ISSUE TITLE
disable password-protected messages if FES is not used

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#1621]

**Comment by tomholub** [comment]
As mentioned in https://github.com/FlowCrypt/flowcrypt-android/issues/1620#issuecomment-1000879583 , we will be merging the functionality in bits an pieces and it will only be enabled for senders on flowcrypt.com domain where we know that FES is running.

Once it's all done and tested and merged, this will be the last issue to do: remove the flowcrypt.com sender restriction, and instead allow the functionality when the user has FES running, otherwise disable it.

On browser extension, during initial setup and when re-fetching client configuration, we store a boolean in local storage, for that user account, to indicate if FES is available. If it is, we never try to get client configuration from flowcrypt.com/api anymore - we always get it from FES going forward.

This boolean is also used when deciding if password protected messages are available.

**Comment by DenBond7** [comment]
@tomholub I'd like to clarify one moment. When do we know that we use FES? When do we have a successful response for `"https://fes.{domain}/api/"`? like

```
{
   "vendor":"FlowCrypt",
   "service":"enterprise-server",
   "orgId":"flowcrypt.com",
   "version":"2022-03",
   "endUserApiVersion":"v1",
   "adminApiVersion":"v1"
}
```

Or should I check some value in this response?

**Comment by tomholub** [comment]
Here https://github.com/FlowCrypt/flowcrypt-android/issues/1202#issuecomment-886685547

`https://fes.{domain}/api/` has to return status 200 that includes `service` to equal `enterprise-server`.
