### ISSUE TITLE
periodically refresh keys from EKM

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#1740]
same as https://github.com/FlowCrypt/flowcrypt-ios/issues/841

**Comment by DenBond7** [comment]
> Each time the app starts, if clientConfiguration.usesKeyManager is true, the app should refetch keys from EKM and update the local ones. The fetch should be in the background, not holding up the app during startup.

@tomholub this issue has similar questions to #1375. 

> Each time the app starts

Could you clarify it?

**Comment by DenBond7** [comment]
One more question. Кespectively to #1168 we have the following

> The goal is that if user has keys already configured on EKM and appropriate OrgRules are in place

Should I follow the same behavior? I mean checking appropriate OrgRules. Or Do I need just to check `orgRules.usesKeyManager()`?

**Comment by DenBond7** [comment]
> which should show error modal on whichever screen will load next

An example(API error)

![image](https://user-images.githubusercontent.com/2863246/165310819-ba4b5384-1d90-43d2-8795-20d53560784d.png)

**Comment by DenBond7** [comment]
> If the pass phrase is not available at that moment, then we display a pass phrase prompt 

![image](https://user-images.githubusercontent.com/2863246/165796748-06ff1eed-7d62-427f-88f1-f09e522f7a2f.png)

**Comment by tomholub** [comment]
This is wrong - all keys that were imported from EKM always have the same pass phrase. Therefore you want to ask for a pass phrase **for the update of all keys** and not for any particular key.

Read the whole conversation starting here https://github.com/FlowCrypt/flowcrypt-ios/issues/841#issuecomment-1103551836

**Comment by DenBond7** [comment]
> all keys that were imported from EKM always have the same pass phrase

I understand that. I've reused `FixNeedPassphraseIssueDialogFragment` that we use to ask a user for at least one pass phrase for existing private keys with a missing pass phrase(`LogicType.AT_LEAST_ONE`)

Here a user sees keys with a missing pass phrase(in our case there will be all keys. Because if we will have at least one private key with a pass phrase we will not show this dialog). For a case where a user will have a few keys we will have the following text:

`Please provide a pass phrase for at least one of the following keys to keep your account keys up to date`

And yes, I understand that there should be the same pass phrase for all imported keys via EKM. But 'FixNeedPassphraseIssueDialogFragment' uses a common logic for all cases where we can have different pass phrases.

Does it look better?

![image](https://user-images.githubusercontent.com/2863246/165803107-e4e23abf-d370-4574-8593-54cda49b239f.png)

**Comment by tomholub** [comment]
All good - thanks :-)
