### ISSUE TITLE
Add native Ukrainian translation

### ISSUE THREAD

**Issue by IvanPizhenko** [FlowCrypt/flowcrypt-android#1884]
Support Ukrainian language in the application.

**Comment by IvanPizhenko** [comment]
@tomholub @DenBond7 what do you think?

**Comment by DenBond7** [comment]
It's a great idea. Would you like to help?

**Comment by tomholub** [comment]
sure

**Comment by IvanPizhenko** [comment]
I think either @DenBond7 or me can do the translation, since we are native speakers.

**Comment by DenBond7** [comment]
@IvanPizhenko I've added a new lang file. Also, I'm adding a `HOW TO` guide.

![image](https://user-images.githubusercontent.com/2863246/177538446-10529147-b5b8-4d55-9c5c-c24bf09ec5fb.png)

![image](https://user-images.githubusercontent.com/2863246/177538751-bcdabd51-4b9b-47d5-ba20-861055cc94d0.png)

Please let me know If you have some free time for this issue. Otherwise, I will do it myself in the near future.

**Comment by IvanPizhenko** [comment]
Thank you, I'll try.
