### ISSUE TITLE
[User feedback] suggests to support at least android 7 (api level 24)

### ISSUE THREAD

**Issue by martgil** [FlowCrypt/flowcrypt-android#1977]
A user cannot install the FlowCrypt app as the user's device only runs Android 7.0. We received a suggestion from the user if we can support Android 7.0.

Also, I look for a resource where we can see an overview of the percentage of the users using a particular android version. https://apilevels.com/ might help.

Screenshot:
<img src=https://user-images.githubusercontent.com/46025304/190298732-da99fb71-037e-4df7-98bd-0008fe265cfe.png width="50%">

Reference: https://mail.google.com/mail/u/human@flowcrypt.com/#inbox/FMfcgzGqQSTcdspSXfGvMRMJLPhzvGKn

**Comment by DenBond7** [comment]
> if we can support Android 7.0.

Hi Mart

1. Unfortunately, it's impossible. We migrated to use Android 8.0(API level 26) as minSdkVersion because we had only a few percentages of older Android versions. And the support of that few percentages took some additional time.
1. Currently Android 13 is the last version. Support very old versions doesn't allow to integrate new features effectively. Android 7.0 was released in 2016. That's too far from nowadays. Especially, when we are talking about the Android system. It is developing very dynamically :)
