### ISSUE TITLE
reply / reply-all / forward on bottom of email

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#202]
I'm missing the options to do actions on bottom of received email. See Gmail app for reference, except that the colors will be either red or green - plain vs encrypted message.

Forward should include the message as well as attachments - you can skip attachments over X MB and warn user if necessary.

**Comment by tomholub** [comment]
Also, red button caption should say "Forward", while green "Forward Encrypted". Same for Reply and Reply all - always add "Encrypted" to caption for green ones.

**Comment by DenBond7** [comment]
for me https://javaee.github.io/javamail/FAQ#forward

**Comment by DenBond7** [comment]
I have discovered JavaMail FAQ (https://javaee.github.io/javamail/FAQ#forward) and found 2 solutions:

1) attach an existing message as an attachment to the new message (the same option as yours)
2) create the new message with the text of the original message included in the new message

I have tried the option 1) and created a new message where I have added the forwarded message (a raw MIME which was downloaded (as you can remember it equals 200 kb)) as an attachment. And in this case, all have looked OK.

But then I have tried forward a message with one attachment equals 800 kb. And in this case, I have received a destructed message. Because the raw MIME message has a size == 200 kb (which include the text message and some part of the attachment).

So need to think about this.

What I can propose (depend on JavaMail FAQ):

**a)** I can use a clear JavaMail way (see 1) ). I can create a reply message and then add an original message as an attachment(I can show a standard attachment view in the create message screen). But I can do that only in the background when I'm sending the message. All will be OK for the standard messages. I can forward any messages(I mean a size). But what to do with encrypted messages? If the forwarded message has a size more than our limit (3 MB) I can't encrypt it. Or we can have a situation when the user has added own attachments to the forwarded message.

**b)** We can use the "inline" case (see 2) ). In this case, I will manage the message parts manually. I can add a text to the forwarded message(as Gmail do that):

```
---------- Forwarded message ----------
From: Den Test <denbond7test@gmail.com>
To: Den <denbond7@gmail.com>
Date: Thu, 22 Mar 2018 09:35:15 +0200
Subject: Standard message with one attachment

The forwarded text here...
```

But here we have a lot of nuances. What to do with HTML and etc.

**c)** I can generate a forwarded message using next algorithm:
- I will add the text or HTML of the original message as an attachment.
- I will add the original message attachments as new attachments and notify a user about size limit (if it has happened).

**Comment by tomholub** [comment]
Try to play around with Gmail and see what exactly does it do. I think it uses the inline forward mechanism.

Currently, FlowCrypt Extension does not forward encrypted attachments (I hope to add that functionality later).

I suggest to use inline, in a format that's very similar to Gmail, and re-attach non-encrypted attachments.

If there are encrypted attachments, I suggest to skip them and show a message that says "Encrypted attachments are not forwarded. Please attach the files if you want them included."

When forwarding encrypted message, you should do something like this:
```


---------- Forwarded message ----------
From: Human at FlowCrypt <human@flowcrypt.com>
Date: 2018-12-30 at 5:08 PM
Subject: Re: FlowCrypt Feedback
To: some.email@gmail.com

Blah blah
Blah
Thanks,
JJ
```

**Comment by tomholub** [comment]
Notice the two empty lines at the top, that's where the user will write their message in case they want to comment the forwarding.

If the forwarded text was encrypted, the handling of the text is the same - put it into the text box for user to see as above.

If the message contained a mix of encrypted and non-encrypted parts, it becomes a mess! We don't have to handle that too well yet, as long as the app doesn't crash, it's ok. Maybe we can create another issue fot that to do later - I would have to create some pseudo code for it.

**Comment by DenBond7** [comment]
Cases for forwarding
- [ ] Standard plain text without attachments 
- [ ] Standard plain text with attachments 
- [ ] HTML text without attachments 
- [ ] HTML text with attachments 
- [ ] An encrypted plain text without attachments 
- [ ] An encrypted plain text with attachments

**Comment by tomholub** [comment]
Plain text is ok for all cases

**Comment by tomholub** [comment]
Looks great!

I'm re-opening this for a design detail: Please use two lines for the icon labels, and change the labels as follows:

```
Reply
Encrypted
```

```
Reply All
Encrypted
````

```
Forward
Encrypted
```

Make sure all are aligned to center with the icon (I think you already do this) and notice the capital letters 
in `Reply All`.

This will visually separate the buttons a little better.
