### ISSUE TITLE
compose message: cannot paste into "add recipient" field

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#218]
tap-and-hold does not produce the "paste" option on my device

**Comment by DenBond7** [comment]
I have disabled this option when I have added "copy" and "remove". Because the paste option conflicts with that functions.

![image](https://user-images.githubusercontent.com/2863246/37862860-be0ecfde-2f5c-11e8-9fe2-6a69db997b3f.png)

I can try to fix that, but I don't know how many time I need for this. The "chips" realization is an extra library. That's the best what I have found, but that's not perfect. I think we need to create an own "chips" implementation. But for this need a lot of time.

**Comment by DenBond7** [comment]
You can change the line https://github.com/FlowCrypt/flowcrypt-android/blob/f41500d62110e68c180c464285554d3a50b70999/FlowCrypt/src/main/java/com/flowcrypt/email/ui/widget/PgpContactsNachoTextView.java#L41 to `this.setLongClickable(true);` and than you will see a result.

**Comment by tomholub** [comment]
I tested it - for now, I suggest that we use the standard prompt for cut/copy/paste and do not show a custom overlay, if we can make it work the following way:
1) when I click on "email bubble", the option should show "cut, copy" (no paste, no other options)
2) when I click in empty space, it should show "paste,select all"
3) It would be awesome if we could add a third custom option in the future when clicking email bubble. Eg "details". Is there such possibility?

**Comment by DenBond7** [comment]
> Eg "details". Is there such possibility?

Yes, it's possible.

**Comment by tomholub** [comment]
Great, I'll test this

**Comment by tomholub** [comment]
I tested this - it needs improvements which I added to next milestone: #253
