### ISSUE TITLE
search inbox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#222]
- should use Gmail search function on Gmail
 - else use standard IMAP search

**Comment by tomholub** [comment]
If too complex, can do all on IMAP for now

**Comment by tomholub** [comment]
Can you please evaluate how long would it take to implement searching? UI similar to Gmail, except it doesn't have to have search history.

1) add search icon on top right
2) when clicked the top will have a search input bar to type
3) the keyboard should have a search icon action button like Gmail does
4) there will also be a back icon, X icon and "No results" page just like Gmail

**Comment by tomholub** [comment]
Understood. We can include that in the current milestone

**Comment by DenBond7** [comment]
I have already made a working variant and you can test my results. I have made an IMAP search, so it will work for all email providers which support a SEARCH function.

But I want to discuss some questions:
1) Currently, the search works only with a single folder. It means we do a search only in an active folder. The search over all folders can take a lot of time if the user has many folders (flowcryptcompatibility is a good example). I have tested the search functionality in Bluemail and there the search takes a lot of time.

The search over all folders takes a lot of time because we need to do:

- open a folder (`IMAP SELECT`)
- do a search (`IMAP SEARCH`)
- close the folder (`IMAP CLOSE`)

2) I don't know but Gmail IMAP Search does't support search using `cyrillic alphabet`. This question is still open for me.

3) Currently, I have added only a search over emails subjects. I can add different combinations of `search keys` from here https://tools.ietf.org/html/rfc3501#page-49

**Comment by tomholub** [comment]
Is there an `all mail` gmail folder? Then you would not have to search through individual folders.

**Comment by tomholub** [comment]
(on gmail)

**Comment by DenBond7** [comment]
> Is there an all mail gmail folder?

No, it's not. It's a folder which is active now.

Here is the IMAP dump:
```
05-01 16:21:50.397 12591-12792/com.flowcrypt.email.debug I/System.out: C3 EXAMINE INBOX
05-01 16:21:50.729 12591-12792/com.flowcrypt.email.debug I/System.out: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $Forwarded $NotPhishing $Phishing Junk)
05-01 16:21:50.730 12591-12792/com.flowcrypt.email.debug I/System.out: * OK [PERMANENTFLAGS ()] Flags permitted.
    * OK [UIDVALIDITY 637035360] UIDs valid.
05-01 16:21:50.730 12591-12792/com.flowcrypt.email.debug I/System.out: * 25349 EXISTS
    * 0 RECENT
05-01 16:21:50.731 12591-12792/com.flowcrypt.email.debug I/System.out: * OK [UIDNEXT 46139] Predicted next UID.
    * OK [HIGHESTMODSEQ 7058505]
    C3 OK [READ-ONLY] INBOX selected. (Success)
05-01 16:21:50.788 12591-12792/com.flowcrypt.email.debug I/System.out: C4 SEARCH SUBJECT test ALL
05-01 16:21:51.498 12591-12792/com.flowcrypt.email.debug I/System.out: * SEARCH 318 620 721 726 784 785 1329 2500 3277 3569 3692 4068 4069 4070 4843 4849 4850 4868 4955 4976 6072 6075 7367 9146 9159 9583 9584 10386 10521 10687 10688 10955 10956 10988 11203 11206 11236 13219 13584 13585 13586 13653 13743 13744 13745 14284 14285 14326 14518 14528 14529 14667 14668 14746 14844 14845 15234 15274 15276 15277 15281 15291 15292 15386 15393 15394 15404 15430 15431 15487 15499 15500 15501 15544 15566 15640 15909 15910 15950 16795 16874 16876 16945 17083 17108 17109 17128 17230 17257 17434 17437 17440 17917 17919 17921 17922 17950 18928 18930 22563 22583 22584 22994 23380 24191 24354 24411 24472 24473 24476 25017 25303 25332 25333 25334 25335
    C4 OK SEARCH completed (Success)
```

To find messages in the `INBOX` I need open this folder and do `SEARCH SUBJECT some text`

**Comment by DenBond7** [comment]
I've added a support of X-GM-RAW (support Gmail syntax via IMAP). Now for Gmail we use X-GM-RAW extension, for other email providers we use the standard way.

> Support a search using Cyrillic alphabet

As it turned out, JavaMail supports the search using the Cyrillic alphabet. I've tested a ukrainian provider and Outlook with Yahoo. All works fine using such email providers. But the search using the Cyrillic alphabet doesn't work on Gmail.

Also, I've created a new question on stackoverflow.com[ JavaMail. IMAP Search using a literal on Gmail](https://stackoverflow.com/questions/50132175/javamail-imap-search-using-a-literal-on-gmail). Short details: the search using the Cyrillic alphabet doesn't work on Gmail because JavaMail automatically send s the command `K2 ENABLE UTF8=ACCEPT` and later use a wrong command to search a text with the Cyrillic alphabet.

Currently, I propose show a warning for the search using the Cyrillic alphabet to the user ("The Cyrillic alphabet doesn't support") for Gmail and open a new issue for this question.

**Comment by DenBond7** [comment]
> Is there an all mail gmail folder?

I've checked the Gmail behaviour. You are right. We can use `All Mail` folder for a searching. For other providers I will do search only in the current folder, for Gmail - in `All Mail` folder.

**Comment by tomholub** [comment]
I was going to look into this - I suspected that on Gmail, All mail would work.

Can you confirm this also includes sent mail? If yes, there should be no issue for Gmail.

**Comment by DenBond7** [comment]
> Can you confirm this also includes sent mail?
I confirm. `All mail` contains sent messages too.

**Comment by tomholub** [comment]
I've tested the search, looks very good to me.

**Comment by tomholub** [comment]
I'm ok to close this even without Cyrillic. You can add an error note when it fails due to searching with foreign alphabets:

"Searching with foreign alphabets not supported yet"

**Comment by DenBond7** [comment]
Ok. I've created a new issue https://github.com/FlowCrypt/flowcrypt-android/issues/259 for Gmail (We can do it later). Now I'm closing current issue.

**Comment by DenBond7** [comment]
> "Searching with foreign alphabets not supported yet"

Oy. Yes, I've forgotten about that.
