### ISSUE TITLE
How to run all tests

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#251]
Can our automated tests be run anywhere? Including the mock-up imap server etc? Or are they windows-dependent?

How do I run all available tests?

**Comment by DenBond7** [comment]
Most of the tests are an IMAP-server depended. Currently, I'm using my local IMAP server.

> Can our automated tests be run anywhere?

We can do that. But in such case, we need a remote IMAP-server. When I started to create tests I was using Outlook test account. But Outlook banned me very soon. (I did a lot of sign-in operations which are maybe strange for Outlook security tools.) That's why I decided to setup my own server where I will be a manager.

> Or are they windows-dependent?

No, they are not. 

> How do I run all available tests?

For running all tests I'm using next command `gradlew connectedDevTestDebugAndroidTest`

**Comment by DenBond7** [comment]
> we need a remote IMAP-server

We need a real IMAP-server. With write url such as example.com. We can't use 123.123.123.123 form.

**Comment by DenBond7** [comment]
What I 'm using now.
![image](https://user-images.githubusercontent.com/2863246/39052021-35904a54-44b3-11e8-8784-cbcb87452ea3.png)

![image](https://user-images.githubusercontent.com/2863246/39051994-196d6fdc-44b3-11e8-9b1d-421195d89979.png)

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/39052073-643f4058-44b3-11e8-8058-f4908282b845.png)

**Comment by tomholub** [comment]
Does this mean that currently Travis will not perform any tests that involve IMAP server?

**Comment by DenBond7** [comment]
Currently, Travis doesn't run any test. I do it manually

**Comment by tomholub** [comment]
Ok. I can give you a VPS to set up an IMAP server for testing. That way we can both run tests.

**Comment by DenBond7** [comment]
![image](https://user-images.githubusercontent.com/2863246/83728935-9e7f6e00-a64f-11ea-8af6-39198cc39e27.png)

**Comment by DenBond7** [comment]
for me https://docs.iredmail.org/sql.create.mail.user.html

**Comment by DenBond7** [comment]
Resolved by #934
