### ISSUE TITLE
save private key as a file: open device folder

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#294]

**Comment by tomholub** [comment]
When I want to save a private key on a device, it will not choose any folder, so the save button is grayed out and I cannot save it until I choose a folder. It confuses me every time:

![screenshot_20181017-013043](https://user-images.githubusercontent.com/6306961/47038925-42837f80-d1b5-11e8-92e1-7793672dd5d3.png)

**Comment by DenBond7** [comment]
@tomholub 

> Is there a way to pre-define a folder to open?

Unfortunately, No there is not. Android doesn't have any settings for that. 

For creating a key we are using [Storage Access Framework (SAF)](https://developer.android.com/guide/topics/providers/document-provider). The Android app which is handling [ACTION_CREATE_DOCUMENT](https://developer.android.com/reference/android/content/Intent.html#ACTION_CREATE_DOCUMENT) 
 (this app is a part of the Android system) can be different from version to version. For example on my Xiami Mi A1 (Android 8.0) the default folder is `Downloads`

**Comment by tomholub** [comment]
I tested a few other apps saving files, and they all seem to be using Download Manager. If we did that, it would presumably be easier, but the file would have to always end up in Downloads. Is that correct?

**Comment by tomholub** [comment]
For now moving it out

**Comment by DenBond7** [comment]
> If we did that, it would presumably be easier, but the file would have to always end up in Downloads. Is that correct?

Yes, it is. [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager) just downloads a file from the given [Uri](https://developer.android.com/reference/android/net/Uri).

[Storage Access Framework (SAF)](https://developer.android.com/guide/topics/providers/document-provider) is a more powerfull solution because it helps to work with different document providers. A user can easy save his private key to Google Drive, Dropbox and to other different places using a couple steps.

I think we can add the third option to the backup options. We can use both methods.
Or we can use [DownloadManager](https://developer.android.com/reference/android/app/DownloadManager)  as a simpler solution.

**Comment by DenBond7** [comment]
> Yes, it is. DownloadManager just downloads a file from the given Uri.

Sorry, I was wrong. DownloadManager can only download HTTP/HTTPS URIs. So we can't use it for our purposes. But we can create a similar solution.

**Comment by tomholub** [comment]
For now, let's leave it as is. We will revisit it when users start complaining about it.

**Comment by DenBond7** [comment]
deprecated
