### ISSUE TITLE
lowercasing emails before use

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#30]
When I used https://attester.cryptup.io/lookup/email, I saw that this API is case sensitive for email parameter.

![2017-05-19_16-52-30](https://cloud.githubusercontent.com/assets/2863246/26725563/c89514d8-47a7-11e7-9552-450c0582c026.png)
![2017-05-19_16-52-57](https://cloud.githubusercontent.com/assets/2863246/26725564/c8a49282-47a7-11e7-9b94-0e6e3365a281.png)

Do I have to manually check that I send the parameter in lowercase? Or maybe it's better for API to solve this issue? As far as I know, it does not matter how to write email address. (For example "denbond7@gmail.com" = "DeNBoND@GmAIL.cOm")

**Comment by tomholub** [comment]
Reopening this as when typing someone's email address, the beginning of the email was capitalized. It stayed that way & the pubkey could not be found as a result.

The email should be lowercased while I'm typing it, or when I'm done typing it, so that it's always lowercased before further processing.

![screenshot_20170615-113434](https://user-images.githubusercontent.com/6306961/27194271-d43b5126-51b6-11e7-9abb-fd7697731e73.png)
