### ISSUE TITLE
encrypted messages sometimes show blank

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#347]

**Comment by tomholub** [comment]
![image](https://user-images.githubusercontent.com/6306961/47352398-55142200-d6a9-11e8-8db5-2ef52557d77a.png)

**Comment by tomholub** [comment]
@DenBond7 what could be causing this? If it's exceptions, can we make it would show that there was an error, and maybe a button that shows the stack trace?

**Comment by tomholub** [comment]
When this happens, it seems that all encrypted messages will start showing as blank. User says killing the app doesn't help. Reportedly a few days later it would start working again, for some time.

ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzKtSDWGdxJjZxmwswbBKjFHph
ref https://mail.google.com/mail/u/0/#inbox/FMfcgxvzLNTBBWplhwTnpvVDznhRTMXt

The user is dev-familiar, so may be able to run a debug apk if needed.

**Comment by DenBond7** [comment]
@tomholub 
As I can see such error happens if we are receiving an empty array using `ProcessedMime.getBlocks()`.

All necessary logic is here
https://github.com/FlowCrypt/flowcrypt-android/blob/af422f140e4439e80719f6363f573546854291f2/FlowCrypt/src/main/java/com/flowcrypt/email/js/tasks/DecryptRawMimeMessageJsTask.java#L55

As I can see we are receiving `ProcessedMime processedMime = js.mime_process(rawMimeMessage);`
Then we are calling 

https://github.com/FlowCrypt/flowcrypt-android/blob/af422f140e4439e80719f6363f573546854291f2/FlowCrypt/src/main/java/com/flowcrypt/email/js/tasks/DecryptRawMimeMessageJsTask.java#L80

But maybe `getMessagePartsFromProcessedMime(jsListener.getContext(), js, processedMime)` returns an empty array. It happens when `ProcessedMime.getBlocks()` returns an empty array. It means that the next line returns a wrong value

https://github.com/FlowCrypt/flowcrypt-android/blob/af422f140e4439e80719f6363f573546854291f2/FlowCrypt/src/main/java/com/flowcrypt/email/js/tasks/DecryptRawMimeMessageJsTask.java#L58

> The user is dev-familiar, so may be able to run a debug apk if needed.

It'll be great. Because I don't know what we can do without that. I can prepare a debug build where I'll add code which will help to understand where we have some errors.

**Comment by tomholub** [comment]
Once this is ready for me to build a debug apk, let me know. We will definitely want to know the `rawMimeMessage` and `processedMime`, and a count of `blocks`.

**Comment by DenBond7** [comment]
@tomholub 
> let me know

I've sent instruction. Please check your email.

**Comment by tomholub** [comment]
Moving to 0.6.9 until we have feedback from user

**Comment by tomholub** [comment]
Still no feedback, moving

**Comment by tomholub** [comment]
Should now be tracked in relevant node issues, or solved
