### ISSUE TITLE
retry toast showed and disappeared too fast

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#353]
I got the following toast when archiving a message: `failed to create new store connection [retry]`

It disappeared before I could click on it.

Could it stay forever until I click retry or cancel?

`failed to create new store connection [retry] [cancel]`

**Comment by DenBond7** [comment]
> Could it stay forever until I click retry or cancel?

I can't do that using [SnackBar](https://developer.android.com/training/snackbar/action). Because there is available only one action. 

This issue will be resolved when I'll close #327. 

But if it needs to fix soon I can try to find another way to show a notification about the error for such problems.

**Comment by tomholub** [comment]
Ok never mind, let's continue in #327.
