### ISSUE TITLE
Use postLookUpEmails instead of postLookUpEmail in UpdateInfoAboutPgpContactsAsyncTaskLoader

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#438]
Currently, here we use a single request for all contacts

https://github.com/FlowCrypt/flowcrypt-android/blob/33d14c37549237d00b59791558981fb6ff95f71c/FlowCrypt/src/main/java/com/flowcrypt/email/ui/loader/UpdateInfoAboutPgpContactsAsyncTaskLoader.java#L102

But here we have API to receive information about all contacts per one transaction

https://github.com/FlowCrypt/flowcrypt-android/blob/33d14c37549237d00b59791558981fb6ff95f71c/FlowCrypt/src/main/java/com/flowcrypt/email/api/retrofit/ApiService.java#L53

It will be great to use `postLookUpEmails` for better performance.

**Comment by tomholub** [comment]
Actually no, I will be deprecating getting more than one email per request (on the backend). It's impossible to cache results because one time you may ask for joe,jane and next time for joe,marie.

When requesting one at a time, it's easier to cache.

One day we could implement http/2 which will really speed it up for the client.

**Comment by DenBond7** [comment]
Got it. So I'm closing it as not actual
