### ISSUE TITLE
optimize decrypt speed

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#45]
Today I spent some time exploring the application.

And it turned out that in the process of displaying detailed information about the message from the raw MIME message, more than 70% takes the process of decrypting.

I mean this code: **js.crypto_message_decrypt(decryptedText);**

com.flowcrypt.email.ui.loader.DecryptMessageAsyncTaskLoader

```
/**
     * Decrypt a message if it encrypted. At now will be decrypted only a simple text.
     *
     * @param js          The Js object which used to decrypt a message text.
     * @param mimeMessage The MimeMessage object.
     * @return <tt>String</tt> Return a decrypted or original text.
     */
    @SuppressWarnings("deprecation")
    private String decryptMessageIfNeed(Js js, MimeMessage mimeMessage) {
        if (TextUtils.isEmpty(mimeMessage.getText())) {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
                return Html.fromHtml(mimeMessage.getHtml(), Html.FROM_HTML_MODE_LEGACY).toString();
            } else {
                return Html.fromHtml(mimeMessage.getHtml()).toString();
            }
        } else {
            String decryptedText = js.crypto_armor_clip(mimeMessage.getText());
            if (decryptedText != null) {
                PgpDecrypted pgpDecrypted = js.crypto_message_decrypt(decryptedText);
                try {
                    return pgpDecrypted != null ? pgpDecrypted.getContent() : "";
                } catch (Exception e) {
                    e.printStackTrace();
                    return mimeMessage.getText();
                }
            } else {
                return mimeMessage.getText();
            }
        }
    }
```
For example, loading and displaying a small encrypted message takes approximately 7 seconds, Of which:

- 2 seconds loading the message (So long, because we want to get a message from the server without attachments. In this case, we need to make additional requests.)
- 3.5 seconds decrypting + 1.5 seconds parsing from the raw MIME message to MimeMessage

**This is normal?**

**Comment by tomholub** [comment]
This is not normal.
I have tested it as well, on my end:
parsing: 50ms (sounds good)
decrypting: 5000ms (very bad)

I found the specific issue in JavaScript where a mathematical computation that takes too much time when run in J2V8. In browser it's super fast. I will investigate it further. Maybe I will let java do that computation instead. I will also file a bug with J2V8.

**Comment by tomholub** [comment]
It was getting slow because of some heavy mathematical computation that is done in JavaScript. I was able to speed it up to 2000ms up by offloading some of it back to Java. But that's a badly designed solution, and still slow anyway.

I will need your help here. There are two possible runtimes in J2V8:

 - V8 runtime that starts using  `V8 v8 = V8.createV8Runtime();`
 - NodeJS runtime that starts using `NodeJS nj = NodeJS.createNodeJS();`
 
I believe the NodeJS library will be order of magnitude faster for our purposes, because it supports these mathematical operations natively.

Unfortunately, the standard J2V8 library does not come precompiled with Node support. Can you please compile a new version of J2V8 using instructions here: https://stackoverflow.com/questions/42574824/how-to-use-nodejs-in-android-using-j2v8 and make sure to enable Node support.

Once that is compiled correctly, the following line should stop failing: `NodeJS nj = NodeJS.createNodeJS();` (add it anywhere you like)

What  `NodeJS nj = NodeJS.createNodeJS();` stops failing, let me know and I will refactor `Js` class to use Node instead.

When done, it should be very fast.

**Comment by DenBond7** [comment]
https://github.com/eclipsesource/J2V8/issues/216

**Comment by tomholub** [comment]
Ouch. I'll come up with a plan B.

**Comment by tomholub** [comment]
I was able to bring it down to 600ms on my phone.

On another account where I'm using a smaller (weaker) key, it's 260ms.

That should be sufficient for now. Later we can do more optimization if we run into issues with attachments.

**Comment by DenBond7** [comment]
It's great. I will test it tomorrow.
