### ISSUE TITLE
decrypt performance degraded

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#457]
In now takes about 15 seconds to decrypt a regular message encrypted with 4096bit key. It used to be about 4 seconds on the same device. I'll send a video separately.

**Comment by DenBond7** [comment]
@tomholub Do you see that performance degradation when you are trying to open the same message repeatedly? Please try open/close/open/close/open..../ close the same message. Because I've tested the app and I don't see any issues about that. Decryption in 0.7.3 has the same performance as the master variant. In the current release, I've changed only handling of MessageBlock.TYPE_PGP_PUBLIC_KEY. But decryption of MessageBlock.TYPE_PGP_MESSAGE has the same code.

**Comment by tomholub** [comment]
When I try repeatedly, it goes from about 9 seconds (first time) down to about 6 seconds (second time). Why the difference?

**Comment by DenBond7** [comment]
If you open a message the first time we need to download the message, decrypt and show it.If you open the message the second time we just decrypt and show the already loaded message. And the difference depends on your internet connection, server response and etc.

**Comment by tomholub** [comment]
I'll move it to later. I think it needs some better tools to profile this.

Maybe a progress bar so that it's clear what's taking up the time. Similar to what we have done in inbox.

**Comment by tomholub** [comment]
superseded by #976

**Comment by tomholub** [comment]
Actually no, performance is still bothering me and it's not clear it's the decryption

**Comment by tomholub** [comment]
closing for the time being, will re-evaluate after we drop node
