### ISSUE TITLE
fixing logo

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#48]

**Comment by tomholub** [comment]
needs more work - wrong logo resolution on login screen

**Comment by tomholub** [comment]
@DenBond7 trying to learn about how to do some basics in Android

1) in `fragment_splash.xml` in the root tag, there is `tools:showIn="@layout/activity_splash"`

This causes me to have a hard time editing the layout, because the layout doesn't show as I edit it, splash shows instead. When I remove it, I can edit fragment_splash easily and it doesn't seem to have any effect when I build the app. What is it for?

2) all of the mipmap images start with `ic_`. Is there some meaning to it? Should I just name all images this way?

**Comment by DenBond7** [comment]
> all of the mipmap images start with ic_. Is there some meaning to it? Should I just name all images this way?

Use common naming conventions for icon assets
https://developer.android.com/guide/practices/ui_guidelines/icon_design.html

**Comment by tomholub** [comment]
Got it, any naming conventions for non-icon images?

**Comment by DenBond7** [comment]
> Got it, any naming conventions for non-icon images?

If it the background image I use **bg_** prefix (bg_big_car.png etc.). For other images, you can use what you like name conventions.

**Comment by DenBond7** [comment]
> This causes me to have a hard time editing the layout, because the layout doesn't show as I edit it, splash shows instead. When I remove it, I can edit fragment_splash easily and it doesn't seem to have any effect when I build the app. What is it for?

It's Android tools. This is used by Android Studio layout editor. When we use tools:showIn="@layout/activity_splash" we mean that current layout will be displayed in activity_splash.xml (on the main screen). But in activity_splash.xml we have next lines:

```
<include
        android:id="@+id/signInView"
        layout="@layout/content_splash"
        android:visibility="gone" />
```
 
**android:visibility="gone"** mean that layout="@layout/content_splash" will not be visible.

That's why you can not see the content in the fragment_splash.xml. More precisely, not even so. You see the layout splash_after_auth.xml because that layout is visible in activity_splash.xml. This situation has happened through the logic that is described in SplashActivity.java.

**Comment by tomholub** [comment]
This will take me some time to get used to. Thanks.
