### ISSUE TITLE
PermissionError regression

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#481]
> since the version from around February 25th I am unable to do just about anything in the android flowcrypt app.
> When I try to load new mails, search existing mails and look up already sent mails I get an 'PermissionError'.
> Since then I've tried to delete the mail account and add it again, uninstall and reinstall the app, etc.
> My phone is a Nokia 7.1 running android pie (February 2019 security update), the mail provider is gmail. The error happens while on a mobile network as well as on WiFi.
> You may find a screenshot of the error attached to this mail.

**Comment by tomholub** [comment]
![SAVE_20190316_173110](https://user-images.githubusercontent.com/6306961/54477526-62c17400-4811-11e9-9573-dea4740cf79e.png)

**Comment by tomholub** [comment]
I set it to 0.7.4 in case it's easy fix. Else we move it to later

**Comment by DenBond7** [comment]
Ok, got it.

**Comment by DenBond7** [comment]
It seems to look like #207. I'll check it.

**Comment by DenBond7** [comment]
I've checked it. A user might see such errors in two cases (As I know):

1. The user has revoked access for Flowcrypt via https://myaccount.google.com/u/0/permissions. Then when the app will try to receive data after a token was refreshed the user will see such error. This option can be easily fixed via reinstall the app.

1. The user has changed a password of his Google account. Then all tokens will become invalid. In that case, the user should resign-in to his Google account on his device and then resign-in in the app.

> I set it to 0.7.4 in case it's easy fix. Else we move it to later

I think we can move it to later. It's an unusual situation and most users won't have such problems. I'll think more about how to resolve such errors. Because it can happen on different screens. So we need to have common behavior for that.

> Since then I've tried to delete the mail account and add it again, uninstall and reinstall the app, etc.

It's strange for me. Maybe here we have a different situation. Because reinstall the app should fix that error.

**Comment by tomholub** [comment]
Ok for now we move it to later

**Comment by tomholub** [comment]
I've just encoutnered something similar:
1) set up the app
2) change password (or in my case, add a phone 2FA)
3) open the app and send email

The email will get stuck in outbox forever, with no error showing!

When you try to reload inbox, it will circle forever, with no error showing.

Bot situations are unacceptable in the same way - when there is error, the user needs to receive feedback that there is error. It's not acceptable that the app gets stuck in a bad state, without showing the error.

**Comment by tomholub** [comment]
Please change

> Please reconnect..

to:

> Please reconnect your account to continue using FlowCrypt with email@domain.com

Everything else stays the same. Thanks!
