### ISSUE TITLE
add second release id

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#561]
@DenBond7 no need to do it during the weekend, I was able to manually build alternative app id by changing the build settings and building it one time, so for now the issue is resolved. Enjoy your Sunday :)

-----------------------

The goal is that two builds would be created with each release:
`com.flowcrypt.email` with file `FlowCrypt-prod-release_.......`
`com.flowcrypt.email.enterprise` with file ``FlowCrypt-enterprise-release_.......``

**Comment by DenBond7** [comment]
@tomholub 
I've added such ability
But with other changes. Because we need an app only with different app_id I've added a new build type (instead of build flavor). This way prevents a lot of copy-paste actions. Now releases look like this

![image](https://user-images.githubusercontent.com/2863246/59179716-9b9c8b00-8b6b-11e9-9dad-d27338affe0b.png)

And one more thing. Because we are going to use one more app_id we have to add changes to the project settings in [Google Developer Console](https://console.developers.google.com/apis/dashboard). We have to allow usage Google API(OAuth) for the package `com.flowcrypt.email.enterprise`
