### ISSUE TITLE
Error: Failed to load labels from the email server

### ISSUE THREAD

**Issue by jbehrends** [FlowCrypt/flowcrypt-android#567]
Android 9
FlowCrypt Version: 0.7.7

I just installed and setup FlowCrypt for the first time on my device.  I've installed it into a "Work Profile" on my phone.
Started the app, selected gmail account, loaded my keyfile, and entered password. 
I now have a screen that says "Failed to load labels from the email server".  
I've tried performing a refresh, and uninstalling and reinstalling the app.  Same error.

**Comment by tomholub** [comment]
Hello @jbehrends , which version of the app are you on?

**Comment by jbehrends** [comment]
@tomholub I'm running v0.7.7

**Comment by DenBond7** [comment]
@jbehrends Thanks for reporting this. Would you be able to test the debug app if I'll prepare it for you? I need some additional info (error details from logs). If yes, please write to human@flowcrypt.com with the subject `FlowCrypt_Android_issue#567`. Thanks!

**Comment by tomholub** [comment]
@DenBond7 I received email from Josh, you can send me the debug build.

**Comment by DenBond7** [comment]
@tomholub I've sent. Check your email box, please.

**Comment by jbehrends** [comment]
Got it!

The error I'm seeing now is:

`[ALERT] IMAP access is disabled for your domain.  Please contact your domain administrator for questions about this feature. (Failure)`

The gmail account I'm using is an enterprise account and IMAP has been globally disabled.

**Comment by DenBond7** [comment]
@jbehrends Thanks a lot. Now I see full details. We already have a hint for such issues. But maybe Enterprise account has a different error message. That's why you didn't see the right hint. I will fix it.

> The gmail account I'm using is an enterprise account and IMAP has been globally disabled.

Unfortunately, currently the Android version of FlowCrypt supports access only via IMAP protocol. It's sad that you are not able to enable IMAP.

**Comment by tomholub** [comment]
@jbehrends is the IMAP restriction in any way configurable on your enterprise account? Or is it an admin decision that you cannot change?

**Comment by jbehrends** [comment]
My company decided to disable it since it posses security risks/challenges..

**Comment by tomholub** [comment]
The typical reason it poses a security challenge is that to connect to IMAP, users have to share their password with the app, and the app has to save the password to connect to IMAP.

However our app uses xoauth 2 (IMAP with oAuth) which is as secure as Gmail API with oAuth. Details: https://developers.google.com/gmail/imap/xoauth2-protocol

Since you are on an enterprise account, there may be a way to whitelist our app for IMAP (considering it's using a more secure mechanism) or maybe allow IMAP over xoauth2. You could raise this with your team.

**Comment by tomholub** [comment]
I'm closing this for now, @jbehrends please feel free to reach out at `human@flowcrypt.com` - maybe we can get your org to relax some of the requirements.
