### ISSUE TITLE
set up ACRA/acralyzer for debugging

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#6]
Need to add Crashlytics for release builds.
https://docs.fabric.io/android/fabric/overview.html

**Comment by tomholub** [comment]
I had to set up a custom ACRA backend because Acralyzer is very finicky, it would not install, CouchDB keeps timing out and giving errors, then when finally installed it was not done properly, etc.. not good.

It will be accepting data in JSON format, see https://github.com/ACRA/acra/wiki/Report-Destinations#data-encoding-formjson

The reporting url is `https://api.cryptup.io/help/acra` - will be deployed in 15 minutes

**Comment by tomholub** [comment]
This will be the last issue I've moved to version 9, so that we can finally release a new version :)

**Comment by tomholub** [comment]
Is this enabled for production builds as well? I have built & signed the app and sent it to someone and it has crashed on them a few times, but I didn't receive any reports from ACRA.

**Comment by DenBond7** [comment]
> Is this enabled for production builds as well?

No, it's not. I will do it now.

**Comment by tomholub** [comment]
kk great

**Comment by tomholub** [comment]
I crashed the debug app with this code:
```Java
    public void crashTheApp() {
        this.crashTheApp();
    }

    public PgpDecrypted crypto_message_decrypt(String data, String password) {
        // db,account_email,encrypted_data,one_time_message_password,callback,force_output_format
        Long start = System.currentTimeMillis();
        V8Array params = new V8Array(v8).push(NULL).push("").push(data).push(password).push
                (cb_catcher).push(NULL);
        this.call(void.class, new String[]{"crypto", "message", "decrypt"}, params);
        Long end = System.currentTimeMillis();
        System.out.println("duration decrypt: " + (end - start));
        this.crashTheApp();
        return new PgpDecrypted((V8Object) cb_last_value[0]);
    }
```
App crashed, Gmail opened, and I don't see report in backend. 

I will test the production build too.

**Comment by tomholub** [comment]
Tested this on production as well. The gmail address shows.

The intended behavior is:
 - when app crashes, ACRA should send report to our backend
 - no email app should come up
 - user should not be prompted. Since these are Alpha releases, we should know about every crash
 - it should not be sent by email, only to our backend

Here is a screen shot after the crash of production build:

![screenshot_20170928-142556](https://user-images.githubusercontent.com/6306961/30989691-667fccee-a453-11e7-96d2-7ecf57d6070c.png)

**Comment by tomholub** [comment]
this is a functioning curl request

The JSON payload can be anything - backend will just save it.
```
curl -X POST \
  https://api.cryptup.io/help/acra \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
    "something": "blahblah", 
    "something_else": "blah"
}'
```

Also Java example:
```Java
OkHttpClient client = new OkHttpClient();

MediaType mediaType = MediaType.parse("application/json");
RequestBody body = RequestBody.create(mediaType, "{\n    \"something\": \"blahblah\", \n    \"something_else\": \"blah\"\n}");
Request request = new Request.Builder()
  .url("https://api.cryptup.io/help/acra")
  .post(body)
  .addHeader("content-type", "application/json")
  .addHeader("cache-control", "no-cache")
  .build();

Response response = client.newCall(request).execute();
```

**Comment by DenBond7** [comment]
https://github.com/FlowCrypt/flowcrypt-android/commit/7764b9f44d83c9ce0c4d4dd78f7142d1bd9fe63f

**Comment by tomholub** [comment]
the backend is now sending emails when it receives a report

the email subject will have a hash of the stack trace, so same errors should group together in email conversation.
