### ISSUE TITLE
run ./gradlew lintProdRelease on semaphore

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#649]
So that ci can fail on linting issues

```
 Lint found errors in the project; aborting build.
  
  Fix the issues identified by lint, or add the following to your build script to proceed with errors:
  ...
  android {
      lintOptions {
          abortOnError false
      }
  }
  ...
  
  Errors found:
  
  /home/luke/git/flowcrypt-android/FlowCrypt/src/main/res/values/strings.xml:277: Error: The resource R.string.cannot_forward_html_emails appears to be unused [UnusedResources]
      <string name="cannot_forward_html_emails">Cannot forward HTML emails yet</string>
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
```

**Comment by DenBond7** [comment]
@tomholub We run `lint` via `lintProdRelease` command. Just exclude it to prevent fail a task

https://github.com/FlowCrypt/flowcrypt-android/blob/8be2dd2537d096b7cfc0ce852e8f1dc014a6746f/script/prod-release.sh#L10

**Comment by tomholub** [comment]
I exactly want it to fail, on CI as well. So I would run:
```
./gradlew lintProdRelease 
```
in the ci

**Comment by tomholub** [comment]
When I run `./gradlew lintProdRelease`

It will actually build the kotlin code before linting it. Is that necessary? I thought it's linting the source, which should be possible without building.

**Comment by DenBond7** [comment]
@tomholub 
> Is that necessary?

Of course. Because `lint` analyses the [bytecode](http://tools.android.com/lint/overview) too.

> build the kotlin code before linting it

You can see the difference between `lintProdRelease` and `assembleProdRelease` here

![image](https://user-images.githubusercontent.com/2863246/61352118-4001a380-a875-11e9-93f1-b1064232e1e5.png)

P.S. 
`--dry-run `
_Run Gradle with all task actions disabled. Use this to show which task would have executed._

I think we can run it before or after tests. Then we will have already compiled code and all tasks before `lintProdRelease` will be skipped

**Comment by tomholub** [comment]
For next release

**Comment by DenBond7** [comment]
@tomholub 
we alredy do that here

https://github.com/FlowCrypt/flowcrypt-android/blob/4c41a1e5437cceacdb7043ba5dd17401c3af4009/.semaphore/semaphore.yml#L43

**Comment by tomholub** [comment]
Great
