### ISSUE TITLE
TypeError: Cannot read property 'subarray' of null

### ISSUE THREAD

**Issue by DenBond7** [FlowCrypt/flowcrypt-android#679]
![image](https://user-images.githubusercontent.com/2863246/62769161-19641080-baa1-11e9-918d-dba4731415f7.png)

```
E/NODEJS-MOBILE: TypeError: Cannot read property 'subarray' of null
        at SecretKey.decrypt ([eval]:70534:29)
        at process.tickCallback (internal/process/nexttick.js:68:7)
```

ref https://mail.google.com/mail/u/2/#search/%22says+cannot+decrypt%22

**Comment by tomholub** [comment]
Actually I got "Your current key cannot open this message." Cannot reproduce

**Comment by tomholub** [comment]
To help me debug it, please set `src += genConst("NODE_PRINT_REPLAY", "true")`, rebuild and open the message. You will see some TypeScript code printed in the stdout.

It's sensitive stuff (contains the private keys etc) so please paste it into a file and send it to me encrypted. Don't try to fix up the code (because it will contain some Java stdout stuff), just send it to me as is.

This will allow me tor "replay" the request on node, and debug it.

Thanks!

**Comment by DenBond7** [comment]
@tomholub I've sent

**Comment by tomholub** [comment]
I could not reproduce it, but this commit should fix it.

**Comment by DenBond7** [comment]
Unfortunately, I have to reopen this issue. I've reproduced it after all changes. (I've seen the error when open 9-th or 10-th message)

**Comment by tomholub** [comment]
Can you please, next time you reproduce it, give me full log, from the moment you open the app, until the failure, with replay=true. Thanks!

**Comment by tomholub** [comment]
Are you sure you were testing on the latest 0.8.4 branch? I went through the whole inbox.

**Comment by tomholub** [comment]
```
I/NODEJS-MOBILE: PgpMsg.decrypt 1
I/NODEJS-MOBILE: PgpMsg.decrypt 2
I/NODEJS-MOBILE: Key.prototype.decrypt
I/NODEJS-MOBILE: SecretKey.prototype.decrypt
I/chatty: uid=10095(u0_a95) NativeNode identical 1 line
I/NODEJS-MOBILE: SecretKey.prototype.decrypt
E/NODEJS-MOBILE: TypeError: Cannot read property 'subarray' of null
        at SecretKey.decrypt ([eval]:70538:29)
        at process._tickCallback (internal/process/next_tick.js:68:7)
```
