### ISSUE TITLE
Message loading stuck at 70% - decrypting

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#753]
This is newly on latest version, several reports

When opening message, it gets stuck on 70% decrypting, even if message was not encrypted.

**Comment by DenBond7** [comment]
@tomholub Are you sure that it's on the latest version?

I've checked code

https://github.com/FlowCrypt/flowcrypt-android/blob/33feaf7dde08c52e9955b6687784b9b139c68f8d/FlowCrypt/src/main/java/com/flowcrypt/email/ui/activity/MessageDetailsActivity.kt#L337

I show 70% after I've loaded a RAW MIME message. So this issue maybe is not related to the latest changes.

One more question
Do you receive info which a version does a user use (via feedback)? If not it'll be a great idea to add this info. And maybe it'll be better to show "Parsing"(or "Processing") instead of "Decrypting". Because a user can be confused when we show "decrypting" for a regular message

**Comment by tomholub** [comment]
Yes - you could say processing.

They all wrote me over email(not feedback form), and said it only happened after update to new version. 

One of them said it only happens for a PGP/mime message.

**Comment by DenBond7** [comment]
@tomholub Are you still receiving reports about this issues?

**Comment by tomholub** [comment]
Not right now

**Comment by tomholub** [comment]
> Aplication is still stoping on 70% decripting :-(

> I installed FlowCrypt to my Samsung Note 4 with Gmail.
> FlowCrypt found my backup key in Gmail and I put my phrase to FlowCrypt so theoretically it should work.

![screenshot](https://user-images.githubusercontent.com/6306961/69449725-6cfa2180-0d53-11ea-985d-716722346c4e.png)

**Comment by DenBond7** [comment]
Got it. It'll be the next issue which I should fix first of all

**Comment by DenBond7** [comment]
@tomholub Currently, we have a timeout of 300 seconds for all requests to Node. So a request can take a long time. It looks like a long request. But why it takes so long I don't know (unfortunately). Currently, `70% Decrypting` means we've sent a request. But we don't receive any success response or errors. I don't know if this is an Android or Node error.

 I've double check code and didn't find a place of a problem. I've added some code to identify a place of the problem. Need to wait while we will receive new feedbacks.

**Comment by tomholub** [comment]
Understood. Can you lower the timeout? 300 seconds is too long. I think 60 seconds is a reasonable maximum.

**Comment by DenBond7** [comment]
Of course. I've reduced that to 60 seconds.

**Comment by tomholub** [comment]
I still had someone say that it took "several minutes" for the timeout, but it was stuck at **85%**, not 70%.

Is it a slightly different issue?

Happens to all received encrypted messages.

![image](https://user-images.githubusercontent.com/6306961/71969958-aa066e80-3242-11ea-990e-94b06266d838.png)

**Comment by tomholub** [comment]
superseded by #976
