### ISSUE TITLE
support multiple email accounts

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#76]
Add a down chevron icon next to my email in the menu. When I click, it should list all current accounts, and last item should say "Add account".

**Comment by tomholub** [comment]
For now, all accounts will use the same set of keys, so no need to set up keys again when adding account. 

However, the account that was just added may also have a key backup. You should check for it, and if it does, ask for pass phrase, verify, then add it to list of keys.

**Comment by tomholub** [comment]
Right now on 0.0.9 branch, when I log out of my account and log under different account, it does not even ask me if I want to import any keys. It goes straight to inbox. There should still be a setup process where it checks backups, and if none, ask me if I want to create key / import key / use current keys.

**Comment by tomholub** [comment]
I thought I saw that screen before, but it didn't show last time I tried on 0.0.9 (2nd account had no backup). Talking about this screen - it should show when adding account and no backups found.

![image](https://user-images.githubusercontent.com/6306961/31367157-2700c926-ad2a-11e7-8100-f55238c188cd.png)

**Comment by DenBond7** [comment]
Basically, I almost complete this task. @tomholub  Please test what already works and if need I will do your comments. 

Now I have next subtasks:

1. Testing the app with switching between accounts.

2. I need help with one situation. How to reproduce it:

- You must be connected to two accounts (account_1 and account_2). And you imported a private key for each account from the email backup.
- Now you select account_1 and do logout
- Then you try to add account_1 again
- You can't add account_1, because we already have the private key of account_1 in the database.

![image](https://user-images.githubusercontent.com/2863246/31500324-c7612a72-af6f-11e7-8363-65032b38d7e8.png)

**Comment by tomholub** [comment]
In this scenario you can indeed just skip the setup screen.

**Comment by tomholub** [comment]
I tested it. I had one crash, but that may have been caused by me (I made edits to the code). I was not able to reproduce the crash again when I git stashed my changes. Looks good.

**Comment by DenBond7** [comment]
I completed this task.
