### ISSUE TITLE
message stuck in outbox

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#769]
I have logged out, logged back in, set up account again

sent a normal encrypted email with attachments from compat account to human@flowcrypt.com

Message stuck in outbox, no feedback about why

There should be a clear feedback about why is it in outbox. Why was it not sent yet? Have there been attempts to send but failed? Has it not even attempted to send yet? etc.

If we cannot make the experience smooth with async sending, well go back to sync. I need errors to always surface to user in a way that is actionable. I would rather that the app is slow but with clear feedback about errors, then fast and wrong.

![image](https://user-images.githubusercontent.com/6306961/68546397-af953300-0410-11ea-9628-d856df9bcf14.png)

**Comment by DenBond7** [comment]
#481

**Comment by DenBond7** [comment]
@tomholub This error happened because we didn't support the Gmail auth issue over the whole app. But now we support that. I've added showing an explanation for such messages which sounds like `Can't send message: auth failure`. But a user will see that only in a case when he will have no connection. In most cases, he will be moved to a screen where he can approve using Gmail access by FlowCrypt.

When you will have tested my changes please let me know if I need to improve something
