### ISSUE TITLE
use acra inline error reporting

### ISSUE THREAD

**Issue by tomholub** [FlowCrypt/flowcrypt-android#99]
This is a customer screenshot

Any way to reasonably debug this without ACRA set up?

![screenshot_20170913-212814](https://user-images.githubusercontent.com/6306961/30409491-4251bcf0-98ba-11e7-8b96-3d3048daa7cb.png)

**Comment by tomholub** [comment]
ref https://mail.google.com/mail/u/1/#inbox/15e6cd66a663d0c9

**Comment by tomholub** [comment]
Nevermind, I have set up ACRA backend

**Comment by DenBond7** [comment]
I think that set up ACRA backend will not help in this situation. Because, the application handle this error and display it.

This error is related to the Js utility. But I don't know why it was happened. I need to see the error stacktrase.

Does user can reproduce this error? Maybe we can prepare the debug build for him.

Or we must handle only know errors and will crash the app if unknown errors will happen. Then ACRA will prepare for user the crash  report dialog. And user if will want will send a crash email to us.

**Comment by tomholub** [comment]
Is there no way to catch and report these errors with ACRA? There must be a way to use ACRA without crashing the app.
```
try {
   ... dangerous code
} catch(..) {
   reportToAcra();
   showError();
}
```

**Comment by tomholub** [comment]
Here, just use this everywhere
```Java
https://stackoverflow.com/questions/12945256/android-acra-with-handled-exceptions
```

**Comment by DenBond7** [comment]
ok, got it

**Comment by tomholub** [comment]
looks good
